# Generated by Django 4.2.3 on 2023-08-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_alter_fotografia_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
