# Generated by Django 4.2.3 on 2023-08-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estado',
            new_name='Escritor',
        ),
    ]
