# Generated by Django 4.2.3 on 2023-08-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_estado_escritor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escritor',
            name='uf',
        ),
    ]
